fastlane_require "dotenv"

before_all do
	Dotenv.load ".env.secret"
end

desc "Create on dev Portal and App Store Connect"
lane :create_app do
  create_app_online #produce
end

platform :ios do
  before_all do
	Dotenv.load ".env.ios"
  end

  desc "Sync signing"
  lane :signing do
	sync_code_signing # match
	mapping = Actions.lane_context[
		SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING
	]
	update_code_signing_settings(
		profile_name: mapping[ENV['MATCH_APP_IDENTIFIER']]
	)
  end

  desc "Build binary"
  lane :build do
	signing
	build_ios_app # gym
  end
  
  desc "Release"
  lane :release do 
	ensure_git_status_clean
	ensure_git_branch
	
	add_git_tag
	push_git_tag

	build
	upload_to_app_store # deliver
	
	reset_git_repo
	
	set_github_release
	end

end
